In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("perceptron_logistic_dataset.csv")

In [3]:
df.head()

   Feature_1  Feature_2  Target
0   0.199247  -0.116976       1
1  -0.248820  -0.731152       1
2  -0.354490  -0.708106       1
3  -1.590865  -2.011992       0
4  -0.200840   1.634932       1

In [8]:
X=df.iloc[0:,:2]
X

    Feature_1  Feature_2
0    0.199247  -0.116976
1   -0.248820  -0.731152
2   -0.354490  -0.708106
3   -1.590865  -2.011992
4   -0.200840   1.634932
..        ...        ...
95  -2.123327   0.661988
96  -1.535998   0.071533
97  -1.460347   0.323236
98   0.836266  -0.345742
99  -0.265706   0.064999

[100 rows x 2 columns]

In [9]:
y=df.iloc[0:,-1]
y

0     1
1     1
2     1
3     0
4     1
     ..
95    0
96    0
97    0
98    1
99    1
Name: Target, Length: 100, dtype: int64

In [18]:
def perceptron(X,y):
    X=np.insert(X,0,1, axis=1)
    weight=np.ones(X.shape[1])
    learning_rate=0.1

    for i in range(1000):
        j=np.random.randint(0,100)
        y_hat=Sigmoid(np.dot(X[j], weight))
        weight=weight + learning_rate * (y[j]-y_hat)*X[j]
    return weight[0], weight[1:]

In [19]:
def Sigmoid(z):
    return 1/(1+np.exp(-z))

In [21]:
b, w = perceptron(X, y)

In [22]:
b

np.float64(2.7422590223371155)

In [23]:
w

array([4.40805615, 0.05045894])