In [24]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score,confusion_matrix

In [3]:
df=sns.load_dataset("iris")

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
df=df.loc[:,['sepal_length','petal_length','species']]
df.head()

   sepal_length  petal_length species
0           5.1           1.4  setosa
1           4.9           1.4  setosa
2           4.7           1.3  setosa
3           4.6           1.5  setosa
4           5.0           1.4  setosa

In [14]:
X=df.iloc[:,0:2]
X

     sepal_length  petal_length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [15]:
y=df.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
encoder=LabelEncoder()
df['species']=encoder.fit_transform(df['species'])

In [12]:
df.head()

   sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [13]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=2)

In [17]:
from sklearn.linear_model import LogisticRegression

In [21]:
# logr=LogisticRegression(multi_class='multinomial')   
logr=LogisticRegression()   #automatically softmax apply hoga
logr.fit(X_train,y_train)

LogisticRegression()

In [27]:
y_pred=logr.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9666666666666667

In [30]:
# print(confusion_matrix(y_test,y_pred))
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0  1  2
0  14  0  0
1   0  7  1
2   0  0  8

In [39]:
logr.predict([[3.4, 2.3]])

C:\Users\Zunaisha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [40]:
logr.predict_proba([[3.4, 2.3]])

C:\Users\Zunaisha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[8.81238155e-01, 1.18719750e-01, 4.20948818e-05]])