In [4]:
import pandas as pd
import numpy as np

In [5]:
df= pd.read_csv('house_price.csv')

In [6]:
df.head(10)

   Area_Marla  Bedrooms  House_Age_years  Distance_to_City_km   Price_PKR
0          34         7               10                 12.5  78492987.0
1          14         2                6                 23.3  17286147.0
2          20         3               27                  7.8  47681169.0
3           9         2                3                 11.0  39737444.0
4          26         1               23                 13.8  72564074.0
5          14         7               28                 24.3  28153985.0
6          12         1               15                  2.0  29326061.0
7          16         5               11                 26.3  33010585.0
8           7         6                4                  3.9  15978063.0
9          31         4               31                 23.3  66364171.0

In [11]:
X=df.iloc[:,0:4]
X

     Area_Marla  Bedrooms  House_Age_years  Distance_to_City_km
0            34         7               10                 12.5
1            14         2                6                 23.3
2            20         3               27                  7.8
3             9         2                3                 11.0
4            26         1               23                 13.8
..          ...       ...              ...                  ...
245          26         1                1                  9.4
246          25         4               24                 12.1
247          35         4               17                 24.8
248           6         3               21                  6.5
249          15         3               25                 29.1

[250 rows x 4 columns]

In [20]:
y=df.iloc[:,4]
y

0      78492987.0
1      17286147.0
2      47681169.0
3      39737444.0
4      72564074.0
          ...
245    57000713.0
246    46138926.0
247    86553840.0
248     5159195.0
249    33404420.0
Name: Price_PKR, Length: 250, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2, random_state=42)

In [23]:
X_train

     Area_Marla  Bedrooms  House_Age_years  Distance_to_City_km
132          26         3               30                  7.8
225          17         2                4                 23.7
238          25         6               26                 17.4
119           7         1               17                 14.6
136          15         7               20                 26.5
..          ...       ...              ...                  ...
106          23         2               24                 13.7
14           22         5                3                  3.4
92           10         4               34                  8.7
179          38         7               39                  8.2
102          17         2               28                 29.2

[200 rows x 4 columns]

In [24]:
y_train

132    68992802.0
225    35269281.0
238    52329270.0
119     3345596.0
136    16693852.0
          ...
106    56461555.0
14     63483701.0
92     11656126.0
179    99331885.0
102    51817272.0
Name: Price_PKR, Length: 200, dtype: float64

In [25]:
X_test

     Area_Marla  Bedrooms  House_Age_years  Distance_to_City_km
142          19         5               36                  3.6
6            12         1               15                  2.0
97           25         6                2                  9.6
60           31         1               23                 15.4
112          27         7               23                 26.5
181          33         4               27                  8.6
197          37         4               27                 29.9
184           7         6               39                 25.8
9            31         4               31                 23.3
104          16         2               13                 11.4
200          17         2               16                  7.9
216          24         2               21                 16.9
236          18         3               30                 15.2
240          10         7               31                  3.5
67           22         3               15                  7.6
224          26         7               30                 20.2
194          23         1               34                 23.2
15           11         1               34                 10.8
177          32         3                3                 10.0
24            3         2               24                 16.8
247          35         4               17                 24.8
19           22         7               14                 23.7
114          12         5                3                 22.4
68           23         6                7                  6.3
176          12         2               21                 16.4
45           39         3               29                 15.7
55           26         4               23                 22.8
10            3         5               37                 14.2
30           31         4               15                 12.5
120          39         2                2                  6.5
201          31         1                1                 22.7
33           12         3               23                  4.6
141           5         4               14                 22.4
219           9         2               20                 24.2
25           12         2                9                  9.9
111          36         6               26                 17.9
18           11         2               24                 25.8
196          12         3               24                 24.3
180          27         4               31                  8.4
159          38         4               11                 10.4
118           7         1               26                  6.9
96            8         4                5                 29.6
108          32         4               19                  4.3
185          20         1               11                  8.5
222          37         7               34                  8.7
16           32         3               21                  3.9
146          32         7               29                 14.8
69           17         1                6                  6.5
173          18         5               17                 11.7
38           15         5                6                 25.3

In [34]:
y_test

142     44874084.0
6       29326061.0
97      70275114.0
60      79921181.0
112     54560840.0
181     80032841.0
197     83081419.0
184     20995379.0
9       66364171.0
104     52571823.0
200     56749955.0
216     72643666.0
236     41877507.0
240     11307014.0
67      58110198.0
224     43105398.0
194     54274113.0
15      10050045.0
177     66244529.0
24       6754375.0
247     86553840.0
19      32871284.0
114     29479620.0
68      47402815.0
176     25434928.0
45      98115855.0
55      52107000.0
10       7269010.0
30      90416294.0
120    101159031.0
201     79291569.0
33      26789659.0
141      7470743.0
219     23437023.0
25      33294400.0
111    104242367.0
18      22153610.0
196     29041114.0
180     81250340.0
159     91812917.0
118      1500000.0
96      26703572.0
108     87766964.0
185     35140484.0
222     93521063.0
16      79585491.0
146     60838768.0
69      39488949.0
173     59745181.0
38      29394520.0
Name: Price_PKR, dtype: float64

In [29]:
y_test.size

50

In [30]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [33]:
lr.predict(X_test.iloc[[0]])

array([46013727.45817756])

In [35]:
lr.predict(X_train.iloc[[0]])

array([63202021.66669193])

In [36]:
lr.predict([[33,6,9,12]])

C:\Users\Zunaisha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([84534155.13607192])

In [37]:
lr.predict([[34,7,10,12.5]])

C:\Users\Zunaisha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([87059510.11848503])