## Using simple linear regression
*Accuracy is not good*

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("cgpa_salary.csv")
df.head()

   Feature_X  Target_Y
0      -9.89    188.53
1      -9.86    196.18
2      -9.67    218.34
3      -9.59    201.25
4      -9.49    161.27

In [3]:
X=df.iloc[:,0:1]
X

     Feature_X
0        -9.89
1        -9.86
2        -9.67
3        -9.59
4        -9.49
..         ...
195       9.39
196       9.40
197       9.44
198       9.71
199       9.74

[200 rows x 1 columns]

In [4]:
y=df.iloc[:,-1]
y

0      188.53
1      196.18
2      218.34
3      201.25
4      161.27
        ...
195    192.65
196    164.34
197    170.67
198    207.85
199    161.64
Name: Target_Y, Length: 200, dtype: float64

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.2, random_state=2)

In [7]:
X_train

     Feature_X
137       3.55
163       6.31
111       0.59
123       2.15
109       0.45
..         ...
43       -6.08
22       -7.84
72       -3.64
15       -8.52
168       6.71

[160 rows x 1 columns]

In [8]:
X_test.size

40

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [14]:
lr.predict(X_test.iloc[[1]])

array([65.88147259])

In [12]:
y_test

112      1.34
29      91.65
182    151.89
199    161.64
193    162.25
85      26.70
10     151.71
54      56.97
115      7.11
35      76.45
12     138.36
92      -4.75
13     161.89
126      2.39
174    108.06
2      218.34
44      48.43
3      201.25
113    -20.30
14     147.99
23     128.58
25     121.29
6      176.03
134     15.66
165     81.95
173    111.70
45      68.19
65      38.71
48      41.63
122     -6.44
178    125.66
64      22.63
9      174.02
57      34.49
78      -8.19
71       4.78
128     17.65
176    144.90
131     30.37
53      44.35
Name: Target_Y, dtype: float64

In [15]:
lr.coef_

array([0.24690467])

In [16]:
lr.intercept_

np.float64(67.6715314494669)

In [17]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [18]:
y_pred=lr.predict(X_test)
score=r2_score(y_test,y_pred)
score

-0.0520732570586373

In [21]:
mse= mean_squared_error(y_test,y_pred)
mse

4815.393644439868

In [22]:
mae=mean_absolute_error(y_test,y_pred)
mae

60.455886492091324

## Using Polynomial linear regression on same dataset

In [23]:
from sklearn.preprocessing import PolynomialFeatures

In [35]:
poly=PolynomialFeatures(degree=2)

In [36]:
X_train_trans=poly.fit_transform(X_train)
X_test_trans=poly.transform(X_test)

In [37]:
X_train_trans[0]

array([ 1.    ,  3.55  , 12.6025])

In [38]:
plr=LinearRegression()
plr.fit(X_train_trans,y_train)

LinearRegression()

In [44]:
y_pred=plr.predict(X_test_trans)

In [41]:
y_test

112      1.34
29      91.65
182    151.89
199    161.64
193    162.25
85      26.70
10     151.71
54      56.97
115      7.11
35      76.45
12     138.36
92      -4.75
13     161.89
126      2.39
174    108.06
2      218.34
44      48.43
3      201.25
113    -20.30
14     147.99
23     128.58
25     121.29
6      176.03
134     15.66
165     81.95
173    111.70
45      68.19
65      38.71
48      41.63
122     -6.44
178    125.66
64      22.63
9      174.02
57      34.49
78      -8.19
71       4.78
128     17.65
176    144.90
131     30.37
53      44.35
Name: Target_Y, dtype: float64

In [45]:
scr=r2_score(y_test,y_pred)
scr

0.9500256286470169

In [46]:
mse= mean_squared_error(y_test,y_pred)
mse

228.7352792055812

In [47]:
mae=mean_absolute_error(y_test,y_pred)
mae

12.231563904268725

In [48]:
plr.coef_

array([ 0.        , -0.1300394 ,  2.02769234])

In [49]:
plr.intercept_

np.float64(1.2486582237923898)